runtime: java
env: flex
liveness_check:
  path: "/actuator/info"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
readiness_check:
  path: "/actuator/info"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 720
automatic_scaling:
  cool_down_period: 120s
  min_num_instances: 1
  max_num_instances: 2    
handlers:
  - url: /.*
    script: this field is required, but ignored
    