runtime: java
env: flex
liveness_check:
  path: "/actuator/info"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
handlers:
  - url: /.*
    script: this field is required, but ignored
    